#!/bin/bash
# DO NOT EDIT THIS FILE

##################################
# Provide MD5 hash
##################################

if [ -x "$(command -v md5)" ]; then
  MD5=md5
elif [ -x "$(command -v md5sum)" ]; then
  MD5=md5sum
else
  cat <<EOF
===========================================================
WARNING: Unable to find a working MD5 command
===========================================================
EOF
fi

$MD5 adv.zip
